# Generated by Django 2.1.7 on 2019-03-18 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('image', models.ImageField(upload_to='food', verbose_name='Изображение')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Острое?')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kind', to='main.FoodKind', verbose_name='Категория блюда')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
