# Generated by Django 2.1.7 on 2019-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cost_on_sale',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена cо скидкой'),
        ),
    ]
